version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "fangyi-zhou"

  # Maintain dependencies for Node
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "fangyi-zhou"

  # Maintain dependencies for Ruby
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "fangyi-zhou"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "fangyi-zhou"
