name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc-ver: ["8.10.5"]

    steps:
    - uses: actions/cache@v2
      name: Cache stack packages
      id: cache-stack
      with:
        path: |
          ~/.stack
          ~/.local
          $GITHUB_WORKSPACE/.stack-work
          $GITHUB_WORKSPACE/_build
          $GITHUB_WORKSPACE/_cache
          $GITHUB_WORKSPACE/_site
        key: ${{ runner.os }}-${{ matrix.ghc-ver }}

    - name: Install stack
      if: steps.cache-stack.outputs.cache-hit != 'true'
      uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        enable-stack: true

    - name: Put stack programs in PATH
      run: echo "~/.local/bin" >> $GITHUB_PATH


    - name: Put stdlib library in Agda library list
      run: |
        mkdir -p ~/.agda/
        touch ~/.agda/libraries
        echo "$GITHUB_WORKSPACE/standard-library.agda-lib" > ~/.agda/libraries
        echo "standard-library" > ~/.agda/defaults

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build
      run: |
        stack -j1 build
        stack -j1 exec site build

    - name: Test
      run: |
        sudo gem install html-proofer
        make test

    - name: Publish
      run: |
        make publish
